CANVAS_WIDTH = 800
CANVAS_HEIGHT = 800
ROWS = 50
COLUMNS = 50
MARGIN = 0
CELL_HEIGHT = CANVAS_HEIGHT // ROWS - MARGIN
CELL_WIDTH = CANVAS_WIDTH // COLUMNS - MARGIN


BACKGROUND = "black"
TEXTCOLOR = "white"
